language: php

dist: xenial

sudo: false

php:
    - 7.3
    - 7.4

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

services:
    - mysql

env:
    global:
        - APP_ENV=test
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"
    - mkdir -p tests/Application/web/media/image

install:
    - composer install --no-interaction --prefer-dist

before_script:
    - (cd tests/Application && bin/console doctrine:database:create -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create -vvv)
    - (cd tests/Application && bin/console assets:install public -vvv)
    - (cd tests/Application && bin/console cache:warmup -vvv)

script:
    - composer validate --strict
    - vendor/bin/ecs check src spec tests/Controller --fix
    - vendor/bin/phpstan analyse -l 1 src/

    - vendor/bin/phpspec run
    - vendor/bin/phpunit
