cart_create_cart:
    path: /create
    methods: POST
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.create_cart

cart_pull_cart:
    path: /pull
    methods: GET
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.pull_cart

cart_update_cart:
    path: /update
    methods: POST
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.update_cart

cart_delete_cart:
    path: /delete
    methods: POST
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.delete_cart

cart_apply_coupon:
    path: /apply-coupon
    methods: POST
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.apply_coupon

cart_delete_coupon:
    path: /delete-coupon
    methods: POST
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.delete_coupon

cart_get_applied_coupon:
    path: /coupon
    methods: GET
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.get_applied_coupon

cart_sync_totals:
    path: /totals
    methods: GET
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.sync_totals

cart_get_payment_methods:
    path: /payment-methods
    methods: GET
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.get_payment_methods

cart_get_shipping_methods:
    path: /shipping-methods
    methods: POST
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.get_shipping_methods

cart_set_shipping_information:
    path: /shipping-information
    methods: POST
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.set_shipping_information

cart_collect_totals:
    path: /collect-totals
    methods: POST
    controller: bitbag_sylius_vue_storefront_plugin.api.cart.collect_totals

